# Generated by Django 5.1.2 on 2024-11-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('stage', 'number'), name='match_stage_number_uniq'),
        ),
    ]
