# Generated by Django 5.1.2 on 2024-11-04 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.stage'),
        ),
    ]
