# Generated by Django 5.1.2 on 2024-11-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_friendscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendscore',
            name='score',
        ),
    ]
