# Generated by Django 5.1.2 on 2024-11-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_friendscore_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendscore',
            name='assists',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='friendscore',
            name='goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
