# Generated by Django 5.1.2 on 2024-11-07 03:59

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_friendscore_assists_friendscore_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participate', models.IntegerField(verbose_name=django.db.models.fields.PositiveSmallIntegerField)),
                ('hit', models.IntegerField(verbose_name=django.db.models.fields.PositiveSmallIntegerField)),
                ('bullseye', models.IntegerField(verbose_name=django.db.models.fields.PositiveSmallIntegerField)),
                ('goals', models.IntegerField(verbose_name=django.db.models.fields.PositiveSmallIntegerField)),
                ('assists', models.IntegerField(verbose_name=django.db.models.fields.PositiveSmallIntegerField)),
                ('advance', models.IntegerField(verbose_name=django.db.models.fields.PositiveSmallIntegerField)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.stage')),
            ],
        ),
    ]
