# Generated by Django 5.1.2 on 2024-11-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='advance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rule',
            name='assists',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rule',
            name='bullseye',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rule',
            name='goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rule',
            name='hit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rule',
            name='participate',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
