# Generated by Django 5.1.2 on 2024-11-26 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_alter_team_options_alter_totalpoint_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchPoints',
            new_name='MatchPoint',
        ),
    ]
