# Generated by Django 5.1.2 on 2024-11-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_alter_rule_advance_alter_rule_assists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='advanced_position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
