# Generated by Django 5.1.2 on 2024-11-26 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_rename_matchpoints_matchpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='matchpoint',
            constraint=models.UniqueConstraint(fields=('friend', 'match'), name='match_point_friend_match_uniq'),
        ),
    ]
