# Generated by Django 5.1.2 on 2024-11-27 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_matchpoint_match_point_friend_match_uniq'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong', models.PositiveSmallIntegerField()),
                ('hit', models.PositiveSmallIntegerField()),
                ('bullseye', models.PositiveSmallIntegerField()),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournaments.stage')),
            ],
        ),
    ]
