# Generated by Django 5.1.2 on 2024-11-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_prediction_away_team_prediction_home_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
