# Generated by Django 5.1.2 on 2024-11-27 19:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_matchpointrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchPoint',
            new_name='PredictionResult',
        ),
    ]
