# Generated by Django 5.1.2 on 2024-11-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_alter_tournament_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='tournament_stage_uniq'),
        ),
    ]
