# Generated by Django 5.1.2 on 2024-11-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_rename_matchpoint_predictionresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictionResult',
        ),
    ]
