# Generated by Django 5.1.2 on 2024-11-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_stage_tournament_stage_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
