# Generated by Django 5.1.2 on 2024-12-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_rename_prediction_groupprediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprediction',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='groupprediction',
            name='home_team',
        ),
    ]
