# Generated by Django 5.1.2 on 2024-12-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_registeredtournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprediction',
            name='away_score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='groupprediction',
            name='home_score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
