# Generated by Django 5.1.2 on 2024-12-11 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_alter_groupprediction_away_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('pld', models.PositiveSmallIntegerField(default=0)),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('draws', models.PositiveSmallIntegerField(default=0)),
                ('losses', models.PositiveSmallIntegerField(default=0)),
                ('gf', models.PositiveSmallIntegerField(default=0)),
                ('ga', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('stage', 'home_team', 'away_team'), name='match_stage_home_team_away_team'),
        ),
        migrations.AddField(
            model_name='grouprow',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouprow',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.stage'),
        ),
        migrations.AddField(
            model_name='grouprow',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.team'),
        ),
        migrations.AddConstraint(
            model_name='grouprow',
            constraint=models.UniqueConstraint(fields=('friend', 'stage', 'team'), name='group_row_friend_stage_team'),
        ),
    ]
