# Generated by Django 5.1.2 on 2024-11-12 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_alter_prediction_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StagePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.stage')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.team')),
            ],
            options={
                'ordering': ['friend', 'stage__tournament', 'stage', 'position'],
                'constraints': [models.UniqueConstraint(fields=('friend', 'stage', 'team'), name='stageprediction_friend_stage_team_uniq'), models.UniqueConstraint(fields=('friend', 'stage', 'position'), name='stageprediction_friend_stage_position_uniq')],
            },
        ),
    ]
