# Generated by Django 5.1.2 on 2024-12-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_grouprow_match_match_stage_home_team_away_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouprow',
            name='position',
        ),
    ]
