# Generated by Django 5.1.2 on 2024-11-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_stageprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageprediction',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
