# Generated by Django 5.1.2 on 2024-11-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0025_stageprediction_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
        migrations.AddField(
            model_name='match',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
