# Generated by Django 5.1.2 on 2024-11-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0027_alter_match_options_alter_match_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-start_time', '-number'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('stage', 'number'), name='match_stage_number_uniq'),
        ),
    ]
